---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/archive-resource-ci}

inputs:
- name: bosh-io-stemcell-resource

run:
  path: bosh-io-stemcell-resource/ci/test
