#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$(mktemp $TMPDIR/bosh-io-stemcell-resource-request.XXXXXX)

cat > $payload <&0

name=$(jq -r '.source.name // ""' < $payload)
version=$(jq -r '.version.version // ""' < $payload)
fetch_tarball=$(jq -r '.params.tarball != false' < $payload)

if [ -z "$name" ]; then
  echo "must specify source name"
  exit 1
fi

if [ -z "$version" ]; then
  echo "must specify version"
  exit 1
fi

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

mkdir -p $destination

stemcell_data=$(mktemp $TMPDIR/bosh-io-stemcell-version.XXXXXX)

curl \
  --silent \
  --retry 5 \
  --fail \
  --location \
  "http://bosh.io/api/v1/stemcells/$name" | \
  jq 'map(select(.version == $version))[0] | .light // .regular' --arg version "$version" > \
  $stemcell_data

url=$(jq -r .url < $stemcell_data)
sha1=$(jq -r .sha1 < $stemcell_data)

if [ "$url" = "null" ]; then
  echo "version $version not found; aborting"
  exit 1
fi

echo "$url" > $destination/url
echo "$version" > $destination/version
echo "$sha1" > $destination/sha1

if [ "$fetch_tarball" = "true" ]; then
  pushd $destination >/dev/null
    curl --retry 5 --fail -L "$url" -o stemcell.tgz
    echo "$sha1  stemcell.tgz" | sha1sum -c -
  popd >/dev/null
fi

jq -n '{
  version: { version: $version },
  metadata: [
    { name: "url", value: $url },
    { name: "sha1", value: $sha1 }
  ]
}' --arg version "$version" --arg url "$url" --arg sha1 "$sha1" >&3
