#!/bin/bash

set -e -u -x

export GOPATH=$PWD/gopath
export PATH=$PWD/gopath/bin:$PATH

cd gopath/src/github.com/concourse/bosh-io-stemcell-resource

go install github.com/concourse/bosh-io-stemcell-resource/vendor/github.com/onsi/ginkgo/ginkgo

ginkgo -r -p "$@"
